# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4310a624b1023b43b214fd143c9fd31f00a51c6ebeff0216db17063295e8ed26c10d85e3cbf6723a752784bfbe926fee6b2cee3dc168048950237f701afb4430

test:
  secret_key_base: 3f231060fe4cb9e08c199e5fcd32b83a2b1ee04e316dd7502294eba2ad38b714aa583d7caa13af3294403be6c7800df64d8bc6bb283607e67c498b739b3964a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
